# 集中管理所有错误码（Python 常量）

# 通用错误码
VALIDATION_ERROR = 'VALIDATION_ERROR'
NOT_FOUND = 'NOT_FOUND'
PERMISSION_DENIED = 'PERMISSION_DENIED'
BAD_REQUEST= 'BAD_REQUEST',
UNAUTHORIZED= 'UNAUTHORIZED',
FORBIDDEN= 'FORBIDDEN',
METHOD_NOT_ALLOWED= 'METHOD_NOT_ALLOWED',
TOO_MANY_REQUESTS= 'TOO_MANY_REQUESTS',
INTERNAL_SERVER_ERROR= 'INTERNAL_SERVER_ERROR',



# 图书模块错误码
BOOK_BUSINESS_ERROR = 'BOOK_BUSINESS_ERROR'   # 自定义业务异常的基类
COVER_IMAGE_TOO_LARGE = 'COVER_IMAGE_TOO_LARGE'
HIGHLIGHTED_BOOK_CANNOT_BE_DELETED = 'HIGHLIGHTED_BOOK_CANNOT_BE_DELETED'
AUTHOR_BANNED = 'AUTHOR_BANNED'
BOOK_ALREADY_BORROWED = 'BOOK_ALREADY_BORROWED'
BOOK_OUT_OF_STOCK = 'BOOK_OUT_OF_STOCK'