"""
Django settings for bookapi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from drf_spectacular.settings import SPECTACULAR_DEFAULTS, spectacular_settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$gh8bvd*)$-(em3)j-4k@c@gofv5o$kremi-b1-&x@f%gprb!o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
#`INSTALLED_APPS` 就像“启用插件”，只有在这里登记过的 App，Django 才会加载它的代码。
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', #配置 Django 启用 DRF
    'rest_framework_simplejwt', #配置 Django 启用 JWT
    'django_filters', #配置 Django 启用 django_filters
    'books', # 配置自定义的app
    'drf_spectacular', # 配置 drf_spectacular，可以使用OpenAPI 3.0

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bookapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    # DRF设置全局分页，所有 ViewSet 自动生效。
    # 这样设置后，**所有继承 `ListModelMixin` 的视图**（如 `ModelViewSet`）都会自动分页！
    # Web 网站（页码导航）设置分页
    # http://127.0.0.1:8000/api/books/
    'DEFAULT_PAGINATION_CLASS': "rest_framework.pagination.PageNumberPagination", #指定默认分页类
    # 移动端 App（滑动加载）设置分页
    # http://127.0.0.1:8000/api/books/?limit=5&offset=10
    # | `limit=5`   | 最多返回5条                |
    # | `offset=10` | 跳过前10条（从第11条开始） |
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 5, # 每页返回多少条数据

    # 配置默认过滤后端
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  #字段精确过滤（如 `?author=张三`）
        'rest_framework.filters.SearchFilter',              #全文搜索（如 `?search=Python`）
        'rest_framework.filters.OrderingFilter',            #排序（如 `?ordering=price`）

    ],
    #
    # === 全局配置认证后端 ===
    # 注意：`DEFAULT_AUTHENTICATION_CLASSES` 是一个列表，可以同时支持多种认证方式！DRF 会按顺序尝试每种认证方式，直到成功
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication', #`启用基于 Session 的认证（浏览器登录后自动携带 Cookie）
        'rest_framework_simplejwt.authentication.JWTAuthentication', # 自动解析请求头中的 `Authorization: Bearer <access_token>`
    ],
    # === 全局配置默认权限 ===
    #  注意：这是**全局设置**，除非某个视图显式覆盖，否则所有接口都必须登录！
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # 默认所有接口都需要登录
    ],
    # === 新增：全局默认限流 ===
    # `'DEFAULT_THROTTLE_CLASSES'`设置全局使用的限流类 只有被列出的限流类才会生效
    'DEFAULT_THROTTLE_CLASSES': [
        # `'AnonRateThrottle'`匿名用户限流类 对未登录用户生效⚠️ 需配合 `DEFAULT_THROTTLE_RATES`
        # 'rest_framework.throttling.AnonRateThrottle', # 匿名用户限流

        # `'UserRateThrottle'`登录用户限流类 对已登录用户生效✅ 常用于普通用户
        # 'rest_framework.throttling.UserRateThrottle', # 登录用户限流

        # 如果使用官方原生的限流类，匿名限流规则能成功，使用自定义限流规则之后，匿名用户限流规则就失效了
        'books.throttling.AdminUserThrottle', # 使用自定义限流类

    ],
    # `'DEFAULT_THROTTLE_RATES'`定义速率规则 指定每个限流类的具体速度✅ 必须和上面对应
    'DEFAULT_THROTTLE_RATES': {
        # `'anon': '5/hour'`匿名用户每小时5次 格式：数字 + / + 时间单位✅ 单位：second, minute, hour, day
        'anon': '5/hour',   # 匿名用户每小时5次
        # `'user': '10/minute'`登录用户每分钟10次 更宽松，适合正常用户✅ 支持小数，如 `3.5/minute`
        'user': '10/minute',# 登录用户每分钟10次
        # 管理员可以高速访问
        # 'admin': '1000/minute', #管理员每分钟1000次
    },

    # 注册自定义异常处理器：`'EXCEPTION_HANDLER'`：告诉 DRF 使用我们写的函数处理所有异常
    'EXCEPTION_HANDLER': 'bookapi.exceptions.custom_exception_handler',
    # 确保 drf-spectacular 是唯一的 schema 提供者
    # 这一行告诉 DRF：“请用 drf-spectacular 提供的 AutoSchema 来生成 API 文档”。
    # 如果不写这行，DRF 可能会继续使用自己的 schema 类，导致冲突。
    # 即使你已经安装了 drf-spectacular，也必须显式设置这个值！
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # ← 必须显式指定！


}

# 配置JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15), # access token 有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), # refresh token 有效期
    'ROTATE_REFRESH_TOKENS': False,         # 刷新时是否换新 refresh token
    'BLACKLIST_AFTER_ROTATION':False,       # 是否拉黑旧 refresh token
}

# 配置媒体文件（上传文件）路径
# | 配置项       | 作用                               | 示例                                |
# | ------------ | ---------------------------------- | ----------------------------------- |
# | `MEDIA_URL`  | 前端访问上传文件的**URL前缀**      | `/media/`                           |
# | `MEDIA_ROOT` | 服务器上实际存放文件的**本地路径** | `E:\Projects\pycharm\bookapi\media` |
# 💡 例如：
# - 上传文件 → 存到 `media/covers/1/cover.jpg`
# - 前端访问 → `http://127.0.0.1:8000/media/covers/1/cover.jpg`
MEDIA_URL = '/media/'  # 前端访问时用的URL路径
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # 实际文件存储路径

# dsf-spectacular 配置
SPECTACULAR_SETTINGS = {
    'TITLE': '图书管理系统API',
    'DESCRIPTION': '这是一个用于管理图书信息的RESTful API.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # 是否在文档页面显示schema
    'COMPONENT_SPLIT_REQUEST': True,  # 将请求和响应参数分开定义（更清晰）
}

# 生产环境部署
# 1. 设置 DEBUG = False （生产环境必须关闭）
# DEBUG = False
# 2. 允许的主机域名（生产环境必须设置）
# ALLOWED_HOSTS = ['your-domain.com', 'www.your-domain.com', '127.0.0.1'] # 替换为你的实际域名ip
# 3.数据库配置（建议使PostgreSQL 或 MySQL）
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'bookapi_db',
#         'USER': 'bookapi_user',
#         'PASSWORD': 'your-strong-password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }
# 4. 静态文件配置（用于 Nginx 提供静态资源）
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' # 存放收集后的静态文件
# 5. 媒体文件配置（上传的图片等）
# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / 'media' # 存放用户上传的文件
# 6. CSRF 安全设置（生产环境建议开启）
# CSRF_COOKIE_SECURE = True # https环境下启用
# CSRF_COOKIE_HTTPONLY = True # 防止XSS攻击
# CSRF_TRUSTED_ORIGINS = ['https://your-domain.com'] # 只允许特定域名发起请求
# 7. Session 安全设置
# SESSION_COOKIE_SECURE = True
# SESSION_COOKIE_HTTPONLY = True
# SESSION_COOKIE_SAMESITE = 'Lax'
# 8. 密钥设置（不要硬编码！ 建议用环境变量）
# SECRET_KEY = 'your-very-secret-key-here' # 生产环境必须设置强密钥
# 9. CORS 设置（如果需要跨域）
# INSTALLED_APPS = [
#     # 其他应用。。。
#     'corsheaders', # 如果你安装了corsheaders
# ]
# MIDDLEWARE = [
#     #。。。其他中间件
#     'corsheaders.middleware.CorsMiddleware',  # 必须放在最前面
#
# ]

# 10. cors配置
# CORS_ALLOWED_ORIGINS = [
#     'https://frontend.your-domain.com',  # 前端域名
#     'http://localhost:3000',             # 开发时本地测试
# ]
# CORS_ALLOW_ALL_ORIGINS = False  # 不允许所有来源（安全建议）
